project:
  type: website
  output-dir: docs

website:
  title: "StatiX AI & Data Labs"
  description: "A collection of technical tutorials and hands-on guides for programming, data science and AI."
  navbar:
    right:
      - href: index.qmd
        text: Home
        icon: house-door
      - href: python.qmd
        text: Python
        icon: filetype-py
      - href: r.qmd
        text: R
        icon: r-circle
      - href: clinical-r.qmd
        text: Clinical R
        icon: heart-pulse
      - href: nextflow.qmd
        text: Nextflow
        icon: diagram-3
      - href: docker.qmd
        text: Docker
        icon: box-seam
      - href: quarto_tutorial_for_beginners.qmd
        text: Quarto
        icon: journal-bookmark
      - href: r-shiny.qmd
        text: R Shiny
        icon: window-stack
      - href: statistics.qmd
        text: Statistics
        icon: calculator
      - href: ml-ai.qmd
        text: ML & AI
        icon: cpu
      - href: about.qmd
        text: About
        icon: info-circle

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 2
    code-fold: true
    code-copy: true
    css: styles.css
    navigation:
      sidebar:
        - text: Nextflow
          href: nextflow.qmd
          icon: diagram-3
        - text: Docker
          href: docker.qmd
          icon: box-seam
        - text: QUARTO
          href: tutorial.qmd
          icon: journal-bookmark
