project:
  type: website
  output-dir: docs

website:
  title: "StatiX AI & Data Labs"
  description: "A collection of technical tutorials and hands-on guides for programming, data science and AI."
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: python.qmd
        text: Python
      - href: r.qmd
        text: R
      - href: clinical-r.qmd
        text: Clinical R
      - href: nextflow.qmd
        text: Nextflow
      - href: quarto_tutorial_for_beginners.qmd
        text: Quarto
      - href: r-shiny.qmd
        text: R Shiny
      - href: statistics.qmd
        text: Statistics
      - href: ml-ai.qmd
        text: ML & AI
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 2
    code-fold: true
    code-copy: true
    css: styles.css
    navigation:
      sidebar:
        - text: Nextflow
          href: nextflow.qmd
        - text: QUARTO
          href: tutorial.qmd
