name: Publish Quarto Website

on:
  push:
    branches:
      - main

jobs:
  publish:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render Quarto website
        run: quarto render

      - name: Commit generated docs
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Build Quarto site to docs [skip ci]"
          file_pattern: docs
          branch: main
          push: true
